// Formats (original DAI look&feel)
const
  SEP_SPACE = ' ';
  SEP_ARG = ',';
  SEP_LIST = ';';
  SEP_STMT = ':';
  SEP_EQUAL = '=';

  TYPE_FLOAT = '!';
  TYPE_INTEGER = '%';
  TYPE_STRING = '$';

  FMT_LINENR = '%d';
  FMT_LINENR_START = '%-7d';
  FMT_LINENR_RANGE = '%d %d';
  FMT_LINENR_RANGEALT = '%d-%d';

  FMT_OPER = '%s';
  FMT_OPERALT = ' %s ';

  FMT_INTEGER = '%d';
  FMT_HEX = '#%x';
  FMT_STRING = '%s';
  FMT_QSTRING = '"%s"';

